name: check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - dev

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou la version que vous utilisez
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run Linter and Formatter
        run: biome ci --error-on-warnings --no-errors-on-unmatched --changed --since="origin/${GITHUB_BASE_REF}" .

      - name: Run Security Audit
        run: npm audit --audit-level=high

      - name: Check TypeScript Compilation (Client)
        run: cd client && npx tsc --noEmit

      - name: Check TypeScript Compilation (Server)
        run: cd server && npx tsc --noEmit